[package]
name = "devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
arch = { path = "../arch" }
bitflags = "1.2.0"
libc = ">=0.2.39"
logger = { path = "../logger" }
vm-memory = { git = "https://github.com/rust-vmm/vm-memory", features = ["backend-mmap"] }
utils = { path = "../utils" }
polly = { path = "../polly" }
virtio_gen = { path = "../virtio_gen" }
